import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx}",
    "./src/modules/**/**/*.{js,ts,jsx,tsx}",
    "./src/components/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    screens: {
      sm: "576px",
      md: "768px",
      lg: "992px",
      xl: "1200px",
      "2xl": "1600px",
    },
    extend: {
      colors: {
        brandViolet: "#5932EA",
      },
      fontFamily: {
        sans: ["sans-serif"],
        poppinsBlack: ["Poppins-Black"],
        poppinsBlackItalic: ["Poppins-BlackItalic"],
        poppinsBold: ["Poppins-Bold"],
        poppinsBoldItalic: ["Poppins-BoldItalic"],
        poppinsExtraBold: ["Poppins-ExtraBold"],
        poppinsExtraBoldItalic: ["Poppins-ExtraBoldItalic"],
        poppinsExtraLight: ["Poppins-ExtraLight"],
        poppinsExtraLightItalic: ["Poppins-ExtraLightItalic"],
        poppinsItalic: ["Poppins-Italic"],
        poppinsLight: ["Poppins-Light"],
        poppinsLightItalic: ["Poppins-LightItalic"],
        poppinsMedium: ["Poppins-Medium"],
        poppinsMediumItalic: ["Poppins-MediumItalic"],
        poppins: ["Poppins"],
        poppinsSemiBold: ["Poppins-SemiBold"],
        poppinsSemiBoldItalic: ["Poppins-SemiBoldItalic"],
        poppinsThin: ["Poppins-Thin"],
        poppinsThinItalic: ["Poppins-ThinItalic"],
        quicksandBold: ["Quicksand-Bold"],
        quicksandLight: ["Quicksand-Light"],
        quicksandMedium: ["Quicksand-Medium"],
        quicksand: ["Quicksand"],
        quicksandSemiBold: ["Quicksand-SemiBold"],
        inter: ["Inter"],
        interBlack: ["InterBlack"],
        interBlackItalic: ["InterBlackItalic"],
        interBold: ["InterBold"],
        interBoldItalic: ["InterBoldItalic"],
        interExtraBold: ["InterExtraBold"],
        interExtraBoldItalic: ["InterExtraBoldItalic"],
        interExtraLight: ["InterExtraLight"],
        interItalic: ["InterItalic"],
        interLight: ["InterLight"],
        interExtraLightItalic: ["InterExtraLightItalic"],
        interLightItalic: ["InterLightItalic"],
        interMedium: ["InterMedium"],
        interMediumItalic: ["InterMediumItalic"],
        interSemiBold: ["InterSemiBold"],
        interSemiBoldItalic: ["InterSemiBoldItalic"],
        interThin: ["InterThin"],
        interThinItalic: ["InterThinItalic"],
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
export default config;
